# Generated by Django 4.2.6 on 2025-03-21 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('module_type', models.CharField(choices=[('data', 'Data Management'), ('form', 'Form Interface'), ('report', 'Reporting'), ('dashboard', 'Dashboard'), ('custom', 'Custom Type')], default='custom', max_length=20)),
                ('has_gui', models.BooleanField(default=False)),
                ('schema', models.TextField(default='{}')),
                ('config', models.TextField(default='{}')),
                ('ui_definition', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ModuleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('state_data', models.TextField(default='{}')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='modules.module')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('schema', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='modules.module')),
            ],
            options={
                'unique_together': {('module', 'name')},
            },
        ),
    ]
